# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0002_project_workers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='Project',
            new_name='MyProject',
        ),
    ]
